#pragma once
#define dt (app.fps.dt())
#define dur (app.fps.dur())
#define scr (app.scr)
#define dscr (app.dscr)
#define vpscr (scr.rect())
#define ft (app.ft)
#define getLocalizedString (app.getLocalizedString)

#define msw (app.input.msw)
#define chs (app.input.chs)
#define msp (app.input.msp)
#define msp_old (app.input.msp_old)
#define msd (app.input.msd)
#define msd_old (app.input.msd_old)
#define msnd (!msd[0] && !msd[1] && !msd[2])
#define msc (app.input.isMouseClickedDown)
#define kbmsg (app.input.kbmsg)
#define kbd (app.input.kbd)
#define kbd_old (app.input.kbd_old)
#define kbc (app.input.isKeyPressedDown)

#define own (app.own)
#define keyboardOwner (own.keyboardOwner)
#define free_kb (own.free_kb)
#define hvd (own.hovered)
#define hoveredDepth (own.hoveredDepth)
#define whd (own.wheeled)
#define whdDepth (own.wheeledDepth)
#define rmv own.remove(this);
#define rhvd (hovered && msnd)
